service: hardyng-serverless

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
plugins:
  - serverless-offline
custom:
  serverless-offline:
    port: 4000
components:
  createSubscription:
    type: aws-lambda
    inputs:
      memory: 512
      timeout: 10
      handler: createSubscription.handler
      root: ./services/subscriptions
      env:
        subscriptionTableName: subscriptions
  getSubscription:
    type: aws-lambda
    inputs:
      memory: 512
      timeout: 10
      handler: getSubscription.handler
      root: ./services/subscriptions
      env:
        subscriptionTableName: subscriptions
  listSubscriptions:
    type: aws-lambda
    inputs:
      memory: 512
      timeout: 10
      handler: getSubscriptionList.handler
      root: ./services/subscriptions
      env:
        subscriptionTableName: subscriptions
  subscriptionsApi:
    type: rest-api
    inputs:
      gateway: aws-apigateway
      routes:
        /subscriptions:
          post:
            function: ${createSubscription}
            cors: true
          get:
            function: ${listSubscriptions}
            cors: true
          /{id}:
            get:
              function: ${getSubscription}
              cors: true
  subscriptionsDb:
    type: aws-dynamodb
    inputs:
      region: us-east-1
      tables:
      - name: subscriptions
        hashKey: id
        indexes:
        - name: SubscriptionIdIndex
          type: global
          hashKey: id
        schema:
          id: number
          name: string
          description: string
        options:
          timestamps: true
