service: hardyng-app-mono-subscriptions

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ../../webpack.config.js
    includeModules: true
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
functions:
  createSubscription:
    handler: create.handler
    events:
    - http:
        path: /
        method: post
        cors: true
        authorizer: aws_iam
  sendSmsMessage:
    handler: sendSms.handler
    events:
    - http:
        path: /
        method: post
        cors: true
        authorizer: aws_iam

resources:
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:custom.stage}-ApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
        - ApiGatewayRestApi
        - RootResourceId
      Export:
        Name: ${self:custom.stage}-ApiGatewayRestApiRootResourceId
